# Ejercicio 2: Matriz TF - IDF
Quishpe Leonardo

In [5]:
import unicodedata
import string
import pandas as pd
from collections import Counter
from sklearn.feature_extraction.text import TfidfTransformer
from IPython.display import display

def preprocesar_texto(texto):
    texto = texto.lower()
    texto = unicodedata.normalize('NFD', texto)
    texto = ''.join(c for c in texto if unicodedata.category(c) != 'Mn')
    texto = texto.translate(str.maketrans('', '', string.punctuation))
    return texto

def cargar_documentos(ruta):
    with open(ruta, 'r', encoding='utf-8') as archivo:
        return [preprocesar_texto(linea.strip()) for linea in archivo]

def construir_vocabulario(documentos):
    return sorted(set(palabra for doc in documentos for palabra in doc.split()))

def construir_matriz(documentos, vocabulario):
    return pd.DataFrame([
        [doc.split().count(palabra) for palabra in vocabulario]
        for doc in documentos
    ], columns=vocabulario)

ruta = '01_corpus_turismo.txt'
documentos = cargar_documentos(ruta)
vocabulario = construir_vocabulario(documentos)
matriz_td = construir_matriz(documentos, vocabulario)

# moostrar la  matriz por terminmos y docs
matriz_td = matriz_td.T
matriz_td.columns = [f'Doc{i+1}' for i in range(matriz_td.shape[1])]

display(matriz_td)

,Doc1,Doc2,Doc3,Doc4,Doc5,Doc6,Doc7,Doc8,Doc9,Doc10,Doc11,Doc12,Doc13,Doc14,Doc15,Doc16
2000,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
a,0,0,0,0,0,0,1,1,0,1,0,0,3,0,0,0
agua,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
alrededor,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
altitud,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
vilcabamba,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
visitan,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
visitantes,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
volcan,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
y,1,0,0,1,1,1,1,0,1,1,1,1,1,1,1,1